# torch activation functions

## [Non-linear Activations (weighted sum, nonlinearity)](https://pytorch.org/docs/stable/nn.html#non-linear-activations-weighted-sum-nonlinearity)

### Sigmoid (0~1)

In [1]:
import torch
from torch import nn

m = nn.Sigmoid()
input = torch.randn(2)
output = m(input)

print(input, output)

tensor([ 0.1470, -1.9911]) tensor([0.5367, 0.1201])


### Tanh (-1~1)

In [4]:
from torch import nn

m = m = nn.Tanh()
input = torch.randn(2)
output = m(input)

print(input, output)

tensor([1.8107, 1.6250]) tensor([0.9479, 0.9253])


### ReLU (0~)

In [5]:
from torch import nn

m = m = nn.ReLU()
input = torch.randn(2)
output = m(input)

print(input, output)

tensor([ 0.1293, -2.1435]) tensor([0.1293, 0.0000])


### LeakyReLU 

In [6]:
from torch import nn

m = m = nn.LeakyReLU(0.1)
input = torch.randn(2)
output = m(input)

print(input, output)

tensor([-0.2640,  0.7024]) tensor([-0.0264,  0.7024])


### PReLU

In [ ]:
from torch import nn

m = m = nn.PReLU()
input = torch.randn(2)
output = m(input)

print(input, output)

### ELU

In [ ]:
from torch import nn

m = m = nn.ELU()
input = torch.randn(2)
output = m(input)

print(input, output)

### CELU

In [ ]:
from torch import nn

m = m = nn.CELU()
input = torch.randn(2)
output = m(input)

print(input, output)

## [Non-linear Activations (other)](https://pytorch.org/docs/stable/nn.html#non-linear-activations-other)

### nn.Softmax (확률)

In [7]:
from torch import nn
import numpy as np

m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
print(input)
print(output)
print(output.sum(dim=1))
print(np.argmax(output, axis=1)) # 최대값의 인덱스를 찾는 함수. max = 최대값 자체를 찾는다.

tensor([[ 0.2422,  0.2882,  0.6019],
        [-0.1839, -0.0858,  0.9286]])
tensor([[0.2874, 0.3009, 0.4118],
        [0.1944, 0.2144, 0.5913]])
tensor([1.0000, 1.0000])
tensor([2, 2])
