# loss functions

## nn.L1Loss

In [1]:
# abs(x-y)

import torch
import torch.nn as nn

loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 1.5635, -0.0165,  2.1463, -0.2796,  0.6402],
        [ 1.0082,  1.7912, -0.1949, -0.2445,  1.9221],
        [ 0.0150,  0.4875,  0.4756, -0.9043, -0.8711]], requires_grad=True)
tensor([[-0.5937,  0.0944,  0.1481,  1.2554, -0.3018],
        [-0.1614, -1.3965,  1.3373, -0.2402, -0.9707],
        [-0.1643, -1.7411,  0.7255,  0.2472,  1.1645]])
1.4249821901321411


## nn.MSELoss

In [2]:
# (x-y)^2

import torch
import torch.nn as nn

loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[-1.8886, -0.5651,  0.3043, -1.0647,  0.7739],
        [-1.8571,  0.7455,  0.3478,  0.4844, -1.5996],
        [ 0.8127,  0.5267, -0.2529,  0.5354, -0.2668]], requires_grad=True)
tensor([[ 0.0937,  0.2047, -0.2170, -0.0715, -0.5362],
        [-1.2361,  1.8752, -1.6884,  0.5661,  0.6265],
        [ 0.3620, -1.1972, -0.4863,  0.8112, -0.8047]])
1.4574605226516724


## nn.CrossEntropyLoss

In [3]:
# C개 아이템을 classify할 때 사용
# input은 (N, C), target은 (N), output은 scalar (N)
# 즉 input중 가장 높은 확률인 아이템이 몇번째인가?가 target이고 그에 따른 loss를 계산한다.

import torch
import torch.nn as nn

loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

print(input)
print(target)
print(output.item())

tensor([[ 0.6596,  1.6158, -0.8915,  0.4191, -0.2218],
        [-0.7644, -1.1341,  0.0340, -1.8193,  0.2917],
        [ 0.0133,  0.2759,  0.3500,  0.2686, -0.6619]], requires_grad=True)
tensor([0, 2, 2])
1.382387638092041


## nn.CTCLoss

In [ ]:
import torch
import torch.nn as nn

# Target are to be padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size
S = 30      # Target sequence length of longest target in batch (padding length)
S_min = 10  # Minimum target length, for demonstration purposes

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()

# Initialize random batch of targets (0 = blank, 1:C = classes)
target = torch.randint(low=1, high=C, size=(N, S), dtype=torch.long)

input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
target_lengths = torch.randint(low=S_min, high=S, size=(N,), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()
print(input)
print(target)
print(loss.item())

 # Target are to be un-padded
T = 50      # Input sequence length
C = 20      # Number of classes (including blank)
N = 16      # Batch size

# Initialize random batch of input vectors, for *size = (T,N,C)
input = torch.randn(T, N, C).log_softmax(2).detach().requires_grad_()
input_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)

# Initialize random batch of targets (0 = blank, 1:C = classes)
target_lengths = torch.randint(low=1, high=T, size=(N,), dtype=torch.long)
target = torch.randint(low=1, high=C, size=(sum(target_lengths),), dtype=torch.long)
ctc_loss = nn.CTCLoss()
loss = ctc_loss(input, target, input_lengths, target_lengths)
loss.backward()
print(input)
print(target)
print(loss.item())

## nn.NLLLoss

In [ ]:
import torch
import torch.nn as nn

m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()

# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss = nn.NLLLoss()
# input is of size N x C x height x width
data = torch.randn(N, 16, 10, 10)
conv = nn.Conv2d(16, C, (3, 3))
m = nn.LogSoftmax(dim=1)
# each element in target has to have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
output = loss(m(conv(data)), target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.PoissonNLLLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.PoissonNLLLoss()
log_input = torch.randn(5, 2, requires_grad=True)
target = torch.randn(5, 2)
output = loss(log_input, target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.KLDivLoss

## nn.BCELoss

In [ ]:
# 분류가 두가지인 경우 사용

import torch
import torch.nn as nn

m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(input), target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.BCEWithLogitsLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.BCEWithLogitsLoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(input, target)
output.backward()
print(input)
print(target)
print(output.item())

## nn.MarginRankingLoss

## nn.HingeEmbeddingLoss

## nn.MultiLabelMarginLoss

In [ ]:
import torch
import torch.nn as nn

loss = nn.MultiLabelMarginLoss()
x = torch.FloatTensor([[0.1, 0.2, 0.4, 0.8]])
# for target y, only consider labels 3 and 0, not after label -1
y = torch.LongTensor([[3, 0, -1, 1]])
output = loss(x, y)
print(x)
print(y)
print(output.item())

## nn.SmoothL1Loss

## nn.SoftMarginLoss

## nn.MultiLabelSoftMarginLoss

## nn.CosineEmbeddingLoss

## nn.MultiMarginLoss

## nn.TripletMarginLoss

In [ ]:
import torch
import torch.nn as nn

triplet_loss = nn.TripletMarginLoss(margin=1.0, p=2)
anchor = torch.randn(100, 128, requires_grad=True)
positive = torch.randn(100, 128, requires_grad=True)
negative = torch.randn(100, 128, requires_grad=True)
output = triplet_loss(anchor, positive, negative)
output.backward()
print(input)
print(target)
print(output.item())